routes/web.php
<?php

use App\Http\Controllers\PostController;
use App\Http\Controllers\WelcomeController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// publica
Route::get('/', [WelcomeController::class, 'index'])->name('welcome.index');
Route::get('welcome/{post}', [WelcomeController::class, 'show'])->name('welcome.show');

// protegidas
Auth::routes();

Route::resource('post', PostController::class);

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'description',
        'user_id'
    ];


    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Api/V1/post/ApiPostController.php
<?php

namespace App\Http\Controllers\Api\V1\post;

use App\Http\Controllers\Controller;
use App\Http\Requests\post\StorePostRequest;
use App\Http\Requests\post\UpdatePostRequest;
use App\Http\Resources\PostResource;
use App\Models\ApiPost;
use App\Models\Post;
use Illuminate\Http\Request;

class ApiPostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return PostResource::collection(Post::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePostRequest $request)
    {
        return (new PostResource(Post::create($request->all())))
        ->additional(['msg' => 'Post Creado con exito'])
        ->response()
        ->setStatusCode(200);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ApiPost  $apiPost
     * @return \Illuminate\Http\Response
     */
    public function show(Post $apipost)
    {
        // dd($post);
        return response()->json([
            'res' => true,
            'msg' => $apipost
        ],200);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\ApiPost  $apiPost
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, Post $apipost)
    {
        $apipost->update($request->all());
        return response()->json([
            'res' => true,
            'msg' => 'Actualizado con exito'
        ],200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ApiPost  $apiPost
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $apipost)
    {
        $apipost->delete();
        if($apipost){
            return response()->json([
                'res' => true,
                'msg' => 'Post Eliminado'
            ],200);
        }else{
            return response()->json([
                'msg' => 'Algo salió mal',
            ],501);
        }
       
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\post\StorePostRequest;
use App\Http\Requests\post\UpdatePostRequest;
use App\Models\Post;
use Illuminate\Http\Request;


class PostController extends Controller
{
    protected $paginationTheme = 'bootstrap';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('can:post.edit')->only('edit','update');
        $this->middleware('can:post.create')->only('create','store');
        $this->middleware('can:post.destroy')->only('destroy');
    }


    public function index()
    {
        
        $posts = Post::where('user_id',auth()->user()->id)->latest('created_at')->get();
        return view('post.index',compact('posts'));
    }
 
    public function create()
    {
        $post = new Post();
        return view('post.create',compact('post'));
    }

    public function store(StorePostRequest $request)
    {
        $request['user_id'] = auth()->user()->id;
        $post = Post::create($request->all());
        return redirect()->route('post.index');
    }

    public function show(Post $post)
    {
        return view('post.show',compact('post'));
    }

    public function edit(Post $post)
    {   
        if (!auth()->user()->hasRole('admin')) {
            $post = Post::where('id',$post->id)->where('user_id',auth()->user()->id)->first();
            if(!$post){
                return back();
            }
        }
        return view('post.edit',compact('post'));
    }

    public function update(UpdatePostRequest $request, Post $post)
    {
        $post->update($request->all());
        return redirect()->route('post.index');
    }

    public function destroy( Post $post)
    {
        $post->delete();
        if ($post) {
            return response()->json([
                'message' => 'Eliminado',
            ]);
        }else{
            return response()->json([
                'message' => 'Algo salió mal',
            ],501);
        }  
    }
}

resources/views/post/create.blade.php
@extends('layouts.app')


@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 p-2">
            <div class="card shadow" style="width: auto;">
                <div class="card-body">
                    <h5 class="card-title"><b>Crear Publicacion</b></h5>
                    <div class="container">
                        <form method="POST" action="{{ route('post.store') }}" enctype="multipart/form-data">
                            @csrf
                            @include('post.partials.fields')
                            <br>
                            <button type="submit" class="btn btn-primary">Crear</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    

@endsection

resources/views/post/edit.blade.php
@extends('layouts.app')


@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12  p-2">
            <div class="card shadow" style="width: auto;">
                <div class="card-body">
                    <h5 class="card-title"><b>Editar Publicacion</b></h5>
                    <div class="container">
                        <form method="POST" action="{{ route('post.update', $post) }}" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            @include('post.partials.fields')
                            <br>
                            <button type="submit" class="btn btn-primary">Guardar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    

@endsection

resources/views/post/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="float-right">
        <a class="btn btn-primary" href="{{ route('post.create')}}" role="button">Agregar Publicación <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
            </svg>
        </a>
    </div>
    <hr>
    <div class="row justify-content-center">
    <!-- @foreach($posts as $post)
        <div class="col-md-6 p-2">
            <div class="card shadow" style="width: auto;">
                <div class="card-body">
                    <h5 class="card-title"><b>{{ $post->title}}</b></h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ date('d-m-Y',strtotime($post->created_at)) }}</h6>
                    <p class="card-text">{{ substr($post->description,0,200) }}</p>
                    <a href="{{ route('post.show', $post) }}" class="btn btn-outline-primary btn-sm">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
                            <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                            <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
                        </svg>
                        Ver
                    </a>
                    @can('post.edit')
                    <a href="{{ route('post.edit', $post) }}" class="m-2 btn btn-outline-success btn-sm">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                        </svg>
                        Editar
                    </a>
                    @endcan
                    @can('post.destroy')
                    <form action="{{route('post.destroy', $post) }}" method="POST" class="btn m-0 p-0">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-sm btn-outline-danger">Eliminar</button>
                    </form>
                    @endcan
                </div>
            </div>
        </div>
        @endforeach -->
        <table id="table_id" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Titulo</th>
                    <th>Opciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach($posts as $post)
                    <tr>
                        <td>{{ $post->title }}</td>
                        <td>
                            <a href="{{ route('post.show', $post) }}" class="btn btn-outline-primary btn-sm">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
                                    <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                                    <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
                                </svg>
                                Ver
                            </a>
                            @can('post.edit')
                            <a href="{{ route('post.edit', $post) }}" class="m-2 btn btn-outline-success btn-sm">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                </svg>
                                Editar
                            </a>
                            @endcan
                            @can('post.destroy')
                            <form action="{{route('post.destroy', $post) }}" method="POST" class="btn m-0 p-0" onclick="eliminar(this)">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-outline-danger">Eliminar</button>
                            </form>
                            @endcan    
                        </td>
                    </tr>
                @endforeach

            </tbody>
        </table> 
    </div>
</div>
@endsection

@section('js')
<script>
    $(document).ready( function () {
        $('#table_id').DataTable({
            order:false,
             language: {
                    "emptyTable": "No hay información",
                "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Mostrar _MENU_ Entradas",
                "loadingRecords": "Cargando...",
                "processing": "Procesando...",
                "search": "Buscar:",
                "zeroRecords": "Sin resultados encontrados",
                "paginate": {
                    "first": "Primero",
                    "last": "Ultimo",
                    "next": "Siguiente",
                    "previous": "Anterior"
                }
            },
        });
    } );

    function eliminar(id){
    event.preventDefault();
    ruta = window.location;
    action = event.srcElement.form.action
    Swal.fire({
        title: 'Estas seguro?',
        icon: 'warning',
        showCancelButton: true,
        confirmButtonText: 'Aceptar',
        cancelButtonText: 'Cancelar',
        confirmButtonColor: '#e65100',
        cancelButtonColor: 'green',
        // timer : 3000,
    }).then((result) => {
        if (result.value) {
            token = $("#token").val()
            console.log(token)
            $.ajax({
                url: action,
                headers: {'X-CSRF-TOKEN' : '{{ csrf_token() }}'},
                type: 'DELETE',
                success: function(result) {
                    if (result) {
                        Swal.fire(
                            'Eliminado!',
                            result.message,
                            'success',
                        )
                        setTimeout(() => {
                            location.reload()
                        }, 1000);
                        
                    }
                },
                error: function (xhr) {
                    Swal.fire({
                    type: 'error',
                    title: 'Oops...',
                    timer:1000,
                    text: xhr.responseJSON.message,
                    })
                }
            })
        }
        return false;
        
        })
    }
</script>


@endsection

resources/views/post/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 p-2">
            <div class="card shadow" style="width: auto;">
                <div class="card-body">
                    <h5 class="card-title"><b>{{ $post->title}}</b></h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ date('d-m-Y',strtotime($post->created_at)) }}</h6>
                    <p class="card-text">{{ $post->description }}</p>
                    <a href="{{ url()->previous() }}" class="card-link">Volver</a>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('js')



@endsection